### ISSUE TITLE
VoteRewards error code with 1.14

### ISSUE THREAD

**Issue by Dowritos** [GeorgeV22-ArtlieX/VoteRewards#11]
06.10 20:09:45 [Server] Votifier NIO worker/INFO Got a protocol v1 vote record from /198.74.57.227:58836 -> Vote (from:MinecraftServers.org username:MinecraftServers.org address:127.0.0.1 timeStamp:1570392584 localTimestamp:1570392585105)
06.10 20:09:45 [Server] Server thread/ERROR Could not pass event VotifierEvent to VoteRewards v2.2.0-Beta
06.10 20:09:45 [Server] INFO org.bukkit.event.EventException: null
06.10 20:09:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:528) ~[CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at com.vexsoftware.votifier.NuVotifierBukkit.lambda$onVoteReceived$1(NuVotifierBukkit.java:368) ~[?:?]
06.10 20:09:45 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:77) [CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:393) [CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:971) [CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:380) [CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:926) [CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:780) [CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
06.10 20:09:45 [Server] INFO Caused by: java.lang.NullPointerException
06.10 20:09:45 [Server] INFO at com.GeorgeV22.VoteRewards.Utilities.UUIDFetcher.getUUIDAt(UUIDFetcher.java:67) ~[?:?]
06.10 20:09:45 [Server] INFO at com.GeorgeV22.VoteRewards.Utilities.UUIDFetcher.getUUID(UUIDFetcher.java:42) ~[?:?]
06.10 20:09:45 [Server] INFO at com.GeorgeV22.VoteRewards.Listeners.VoteListeners$1.run(VoteListeners.java:39) ~[?:?]
06.10 20:09:45 [Server] INFO at com.GeorgeV22.VoteRewards.Listeners.VoteListeners.onPlayerVote(VoteListeners.java:104) ~[?:?]
06.10 20:09:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
06.10 20:09:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
06.10 20:09:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
06.10 20:09:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
06.10 20:09:45 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[CraftBukkit_Latest_1.14.4.jar:git-Bukkit-7deb372]
06.10 20:09:45 [Server] INFO ... 11 more

**Comment by Dowritos** [comment]
please help 🆘

**Comment by GeorgeV22-ArtlieX** [comment]
Fixed in new version!
