### ISSUE TITLE
sometimes error after vote (reward 1 diamond)

### ISSUE THREAD

**Issue by Yamiru** [GeorgeV22-ArtlieX/VoteRewards#4]
07.07 15:33:35 [Server] WARN [VoteRewards] Starting VoteParty
07.07 15:33:35 [Server] WARN [VoteRewards] Plugin VoteRewards v2.2.0-Beta generated an exception while executing task 11043
07.07 15:33:35 [Server] INFO java.lang.IllegalStateException: VotePartyStartEvent may only be triggered synchronously.
07.07 15:33:35 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:524) ~[patched_1.14.3.jar:git-Paper-124]
07.07 15:33:35 [Server] INFO at com.GeorgeV22.VoteRewards.Utilities.VoteParty$3.run(VoteParty.java:210) ~[?:?]
07.07 15:33:35 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-124]
07.07 15:33:35 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.3.jar:git-Paper-124]
07.07 15:33:35 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.3.jar:git-Paper-124]
07.07 15:33:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
07.07 15:33:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
07.07 15:33:35 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by GeorgeV22-ArtlieX** [comment]
Hello,
Sorry for the late respond. This error is because paper do not allow asynchronously events.
This will be fixed in the new version
