### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by Altraze** [GeorgeV22-ArtlieX/VoteRewards#5]
Hello, i have somle lag isseus with voterewards
https://timings.aikar.co/?id=183e93cf0b4246edbf66c14357cfdea2

**Comment by GeorgeV22-ArtlieX** [comment]
Hello,
is becaus

**Comment by GeorgeV22-ArtlieX** [comment]
Hello,
this lag is not from voterewards but from the other plugins commands
